name: Benchmark

on: [workflow_dispatch]

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Volta
      uses: volta-cli/action@v1
    
    - run: yarn

    - run: yarn bootstrap:benchmark

    - run: yarn benchmark

    - uses: EndBug/add-and-commit@v7
      with:
        add: 'benchmark/README.md'
